# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pr:
- master

pool:
  vmImage: 'ubuntu-latest'

container: rust:stretch

steps:
- script: find $(Build.SourcesDirectory)/src -name '*.rs' -exec rustfmt --check {} \;
  displayName: 'Rust Format Check'
