[package]
name = "rcon"
version = "0.1.0"
authors = ["Scott Hussey <sthussey@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "rcon"
path = "src/cli/rcon.rs"

[dependencies]
